name: Build

on:
  push:
    branches: [ "**" ]
  schedule:
   - cron: "1 0 * * *"

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 21
                uses: actions/setup-java@v4.2.1
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Build with Gradle
                uses: gradle/actions/setup-gradle@v3
                with:
                    arguments: build
            -   name: Upload a Build Artifact
                uses: actions/upload-artifact@master
                with:
                    # Artifact name
                    name: SkBee-Artifact
                    # A file, directory or wildcard pattern that describes what to upload
                    path: build/libs/SkImagining*.jar
